service: example

# Cloud Provider
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  lambdaHashingVersion: 20201221
  versionFunctions: false

# functions
functions:
  getCoinList:
    handler: src/functions/getCoinList.handler
    events: # The events that trigger this function
      - http:
          path: coin/getCoinList
          method: get
  updateFavoriteCoinList:
    handler: src/functions/updateFavoriteCoinList.handler
    events:
      - http:
          path: coin/updateFavoriteCoinList
          method: post
  statCoin:
    handler: src/functions/statCoin.handler
    events:
      - http:
          path: coin/statCoin
          method: post
  cronRushCoin:
    handler: src/functions/cronRushCoin.handler
    events:
      - schedule: rate(1 hours)
      - schedule: cron(0 12 * * ? *)
  cronTargetPriceAlert:
    handler: src/functions/cronTargetPriceAlert.handler
    events:
      - schedule: rate(1 hours)
      - schedule: cron(0 12 * * ? *)

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline

# Resources your functions use
resources:
  Resources:
    # SNS Topics
    SNSHelloEvent:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Hello Event Topic
        TopicName: hello-event
